packages:
  - packages/*
  - apps/**
  - '!**/test/**'

syncInjectedDepsAfterScripts:
  - build

injectWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild"

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  cookie@<0.7.0: '>=0.7.0'
  vite@>=6.3.0 <=6.3.3: '>=6.3.4'
