on:
  workflow-dispatch

jobs:
  redepoly:
    name: "re-deploy infrastructures"
    runs-on: docker

    steps:
    - name: "Checkout the compose file"
      uses: actions/checkout:v4
      with:

    - name: "Re-start"
      run:
        docker compose -f docker-compose.yml up -d
    
