on:
  workflow_dispatch:
    inputs:
      services:
              description: "Select services to deploy"
              required: true
              type: choice
              options:
                - timescaledb
                - rabbitmq
                - pgadmin
                - all

jobs:
  redepoly:
    name: "re-deploy infrastructures"
    runs-on: docker

    steps:
    - name: "Checkout compose file only"
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          deploy
        sparse-checkout-cone-mode: false

    - name: Deploy selected service(s)
      run: |
        case "${{ github.event.inputs.services }}" in
          timescaledb)
            docker compose --project-name ${{github.repository}} up -d db
            ;;
          rabbitmq)
            docker compose --project-name ${{github.repository}} up -d broker
            ;;
          pgadmin)
            docker compose --project-name ${{github.repository}} up -d pgadmin
            ;;
          all)
            docker compose --project-name ${{github.repository}} up -d db broker pgadmin
            ;;
        esac
  
